spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://localhost:5434/patient_db
    username: patient_user
    password: patient_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  jwt:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem
    expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: health, beans, mappings

server:
  port: 8083
